.github/workflows/deploy-to-sandbox.yml
* tiny fix, fixes the stack name to either `entities` or `mutations`
=> fix stack name

.gitattributes, workflows/api/helpers/workflow.py, workflows/api/helpers/workflow_run.py, workflows/api/helpers/workflow_run_entity_input.py, workflows/api/helpers/workflow_run_step.py, workflows/api/helpers/workflow_version.py, workflows/api/schema.graphql, workflows/api/schema.json, workflows/api/types/workflow.py, workflows/api/types/workflow_run.py, workflows/api/types/workflow_run_entity_input.py, workflows/api/types/workflow_run_step.py, workflows/api/types/workflow_version.py, workflows/cli/gql_schema.py
Follow up to https://github.com/chanzuckerberg/czid-platformics/pull/197
Just ran `make codegen` in the workflows service to allow groupby clauses in aggregate queries.
=> [CZID-9230] Run codegen to update workflows

entities/api/schema.graphql, entities/api/schema.json, entities/api/types/sequencing_read.py, entities/api/validators/sequencing_read.py, entities/cli/gql_schema.py, entities/schema/platformics.yaml, platformics/client/entities_schema.py
During file upload, we need to create SequencingRead, but can only link PrimerFile once the upload completes
=> Make primer file updatable

entities/api/files.py, entities/api/schema.graphql, entities/api/schema.json, entities/cli/gql_schema.py, entities/database/models/file.py, entities/test_infra/factories/metric_consensus_genome.py, platformics/client/entities_schema.py
This PR exposes file timestamps and upload errors in the GQL results. Also fix the issue with FuzzyFloat.
=> Expose file timestamps

workflows/api/main.py
These need to be loaded in properly if this endpoint is split with loaders running at run workflow.
=> SQLAlchemy fix

workflows/api/main.py
=> Fix some workflow join stuff.

workflows/api/main.py
We need the name in the run section not in the create section.
=> fix sqlalchemy loading position

platformics/util/seed_utils.py
Not sure why this didn't work but this should fix it.
=> fix upsert bucket issue

entities/api/files.py, entities/schema/platformics.yaml
This PR adds some clarifying comments to File objects in the YAML schema and GQL mutations.
=> Add clarifying comments

entities/poetry.lock, entities/pyproject.toml, workflows/poetry.lock, workflows/pyproject.toml
=> bump fastapi version

entities/.happy/terraform/envs/dev/iam_policies.tf, entities/.happy/terraform/envs/sandbox/iam_policies.tf, entities/.happy/terraform/envs/staging/iam_policies.tf
* adds permissions to entities iam user for s3 buckets
=> add permissions to s3 bucket entities

.github/workflows/deploy-to-development.yml, .github/workflows/reusable-deploy.yml
* small fixes to dev deploy script
=> Rename dev deploy script

workflows/plugins/output_loaders/entities/bulk_download_output.py
The download type update should be applied automatically.
=> remove display name from bulk downloads

entities/scripts/seed/bulk-download.py, platformics/util/seed_utils.py, workflows/api/loader/loader.py, workflows/docker-compose.yml, workflows/plugins/event_bus/redis/event_bus_redis.py, workflows/plugins/event_bus/swipe/event_bus_swipe.py, workflows/plugins/plugin_types.py, workflows/settings.py
This allows event bus implementations to decide whether or not to commit messages.
=> Restructure event bus to allow them to control message commit behavior

platformics/codegen/tests/test_bulk_download_policy.py
Forgot to update the comment when making this new test 🤦
=> Update comment in test

workflows/.happy/terraform/envs/sandbox/iam_policies.tf, workflows/.happy/terraform/envs/staging/iam_policies.tf, workflows/plugins/event_bus/swipe/event_bus_swipe.py, workflows/plugins/output_loaders/entities/consensus_genome_output.py
* fixes some IAM policies and handles 0 atcg counts
=> fix policies and handle count 0 atcg

workflows/plugins/output_loaders/entities/consensus_genome_output.py
=> fix missing gc percent

.github/workflows/create-development-environment.yml
* testing for creation of dev remote environments
=> add dev environments

.github/workflows/create-development-environment.yml, .github/workflows/reusable-deploy.yml, workflows/.happy/terraform/envs/dev/main.tf, workflows/plugins/event_bus/swipe/event_bus_swipe.py
* fixes the create dev environment action
=> create dev enviroment fixes

.github/workflows/deploy-to-prod.yml, entities/.happy/config.json, workflows/.happy/config.json
* creates a prod deploy github action
=> create prod deploy github action

.github/workflows/deploy-to-prod.yml
https://czi.atlassian.net/browse/CCIE-3911
=> chore: remove deprecated tags
